project:
  type: website

website:
  title: "School Choice"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Analysis
        menu:
          - href: school_types.qmd
            text: Types of School 
          - href: school_level.qmd
            text: School-Level
          - href: differences.qmd
            text: Differences among Schools
      - href: sources.qmd
        text: Sources
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



