project:
  type: website

website:
  title: "School Choice"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sources.qmd
        text: Sources
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



